### ISSUE TITLE
external source of contact

### ISSUE THREAD

**Issue by kad-ecoli** [mskwark/PconsC3#1]
I would like to run PconsC3 locally. Unfortunately, it depends on external source of contact: PhyCMAP or CMAPpro, neither of which can be generated from standalone program. I wonder whether there is other source of contact I can used/

**Comment by mskwark** [comment]
PhyCMAP is (was?) a part of RaptorX package, which can be freely downloaded from authors' website (http://raptorx.uchicago.edu/download/). While the method has been tested thoroughly on phyCMAP predictions, we strongly believe that any (relatively) reliable prior on contact propensities would do just as well. It is of importance, that the method does not rely on coevolution, but rather is based on observed contact propensities of certain amino acid windows. If not phyCMAP, maybe you could consider DNcon from MULTICOM package (http://sysbio.rnet.missouri.edu/multicom_toolbox/tools.html)...  But any source of contacts should work.

**Comment by arneelof** [comment]
PS. If you want to use something faster, better and in particular easier to
install use PconsC4.

**Comment by kad-ecoli** [comment]
[1] Where can I find PhyCMAP from RaptorX package? The download page contain the following files:
README
0README.AUCpreD.txt
0README.DeepAlign.txt
0README.EPAD.txt
0README.MRFalign.txt
0README.RaptorX.txt
0README.data4contactPrediction.txt
AUCpreD_v1.03_release.tar.gz
CAL_EPAD.tar.gz
CAL_TGT.tar.gz
CNFpred-UserGuide.pdf
CNFsearch1.66_release.zip
DeepAlign_Open_v1.13.benchmark.tar.gz
DeepAlign_Open_v1.134.tar.gz
DeepCNF_SS_v1.02_release.tar.gz
EPAD_SCOP40.tar.gz
EPAD_package_v1.01.tar.gz
MRFsearch0.90_release.tar.gz
Mems510-PredictedContacts-byNonMPs.tar.gz
RaptorX_Property_Fast_v1.01.tar.gz
TGT_SCOP40.tar.gz
TPL_BC40_20180228.tar.gz
TPL_Remain_20180228.tar.gz
TemplateLists_20180228.tar.gz
nr70.tar.gz
nr90.tar.gz
pdb25-6767-train.release.contactFeatures.pkl
pdb25-6767-valid.release.contactFeatures.pkl
pdb25-test-500.release.contactFeatures.pkl
pdb_BC40_20180228.tar.gz
pdb_Remain_20180228.tar.gz 
It seems none of them is contact prediction program.

[2] Where can I find PconsC4?

**Comment by arneelof** [comment]
For PhyCMAP you have to contact the authors. However, I think it might be
easier to use some alternative version as suggested by Marcin.

PconsC4 instuctions:
if you want to use PconsC4 on an alignment (in .a3m format) it should work
with the following steps:

1) Clone PconsC4:
git clone https://github.com/ElofssonLab/PconsC4.git

2) Get the trained model
wget https://www.dropbox.com/s/kgyz31he9q6fkoi/pconsc4_unet.python3.h5
<https://www.dropbox.com/s/kgyz31he9q6fkoi/pconsc4_unet.python3.h5?dl=0> -O
src/model/pconsc4_unet.python3.h5

3) Run PconsC4 on an aligment:
python src/run_pconsc4.py <path_to_alignment.a3m> [-o <path_to_output_file>
-t <number_of_threads> -s <min_sequence_separation>]

Compiling the cython source code is now done automatically when running
"src/run_pconsc4.py" for the first time. So no need to do it manually with
the provided setup.py script anymore.





Yours

Arne

-----------------------------------------
  Arne Elofsson                  Science for Life Laboratory
  Tel:+46-(0)70 695 1045   Stockholm University
  http://bioinfo.se/               Box 1031,
  Email: arne@bioinfo.se   17121 Solna, Sweden
  Twitter:   https://twitter.com/arneelof
  Scholar: http://scholar.google.se/citations?user=s3OCM3AAAAAJ
  ORCID: 0000-0002-7115-9751

**Comment by kad-ecoli** [comment]
git clone https://github.com/ElofssonLab/PconsC4.git
Cloning into 'PconsC4'...
remote: Repository not found.
fatal: repository 'https://github.com/ElofssonLab/PconsC4.git/' not found

This means that either the repository does not exist on github, or your have set special permission (such as making the repository private) to forbid the public from downloading it. Is there some other way I can download PconsC4?
